# Numpy

https://numpy.org/doc/stable/

In [104]:
%%capture
!pip instal numpy

In [105]:
import numpy as np

##### Array Unidimensional

In [106]:
# Criar array unidimensional
unid = np.array(
    [10,20,30,40]
)
unid

array([10, 20, 30, 40])

In [107]:
#Verificar shape do array
unid.shape

(4,)

In [108]:
#Verificar número de dimensões
unid.ndim

1

##### Array Bidimensional

In [109]:
# Criar array bidimensional
bidim = np.array([
    [100,83,15],
    [42,78,0]
])
bidim

array([[100,  83,  15],
       [ 42,  78,   0]])

In [110]:
bidim.shape #(linhas,colunas)

(2, 3)

In [111]:
bidim.ndim

2

In [112]:
bidim.max()

100

##### Arange

In [113]:
array3 = np.arange(15)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
array4 = np.arange(0,15,3)
array4

array([ 0,  3,  6,  9, 12])

#### Linspace

In [115]:
array5 = np.linspace(0,3,4)
array5

array([0., 1., 2., 3.])

#### zeros

In [116]:
array6 = np.zeros((10,8))
array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### ones

In [117]:
array7 = np.ones((2,3,2))
array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### eye

In [118]:
array8 = np.eye(3)
array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### diag

In [119]:
array9 = np.diag((2,1,4,6))
array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

#### random

In [120]:
array10 = np.random.randn(5)
array10

array([-1.18118245, -0.44905686,  0.25009695, -0.96637964, -0.86610867])

#### random normal distributed

In [121]:
array11 = np.random.randn(5)
array11

array([-0.7471538 , -1.31188798, -0.31648791, -1.43593677,  0.41291933])

#### empty

In [122]:
array12 = np.empty((3,2))
array12

array([[9.828357e-317, 0.000000e+000],
       [0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000]])

### tile

In [123]:
array13 = np.array([
[9,4],
[3,7]
])
np.tile(array13,4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [124]:
np.tile(array13,(2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

#### Data Types

In [125]:
array13 = np.array([8,-3,5,9],dtype = 'float')
array13

array([ 8., -3.,  5.,  9.])

In [126]:
array13.dtype

dtype('float64')

In [127]:
array14 = np.array(['hi',-3,5.0,9])
array14.dtype

dtype('<U32')

In [128]:
array15 = np.array(['hi','how','are','you'])
array15.dtype

dtype('<U3')

In [129]:
array16 = np.array([True,False, True])
array16.dtype

dtype('bool')

In [130]:
array17 = np.array([True,False, True])
array17.astype(int)

array([1, 0, 1])

#### Operações

In [131]:
operado = np.arange(1,6)
operado


array([1, 2, 3, 4, 5])

In [132]:
operado * 5

array([ 5, 10, 15, 20, 25])

In [133]:
operado ** 4

array([  1,  16,  81, 256, 625])

In [134]:
operado + 1

array([2, 3, 4, 5, 6])

In [135]:
operado2 = np.arange(1,11,2)
operado2

array([1, 3, 5, 7, 9])

In [136]:
operado + operado2

array([ 2,  5,  8, 11, 14])

In [137]:
operado - operado2

array([ 0, -1, -2, -3, -4])

In [138]:
operado * operado2

array([ 1,  6, 15, 28, 45])

In [139]:
operado / operado2

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556])

In [140]:
operado % operado2

array([0, 2, 3, 4, 5])

In [141]:
operado == operado2

array([ True, False, False, False, False])

In [142]:
operado > operado2

array([False, False, False, False, False])

In [143]:
np.logical_and(operado,operado2)

array([ True,  True,  True,  True,  True])

#### Fastest array

In [144]:
array_numpy = np.arange(10**6)
array_python = range(10**6)

In [145]:
%timeit array_numpy ** 4

1.52 ms ± 6.63 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [146]:
%timeit [value ** 4 for value in array_python]

188 ms ± 887 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Index e slicing

In [147]:
to5 = np.array([1,2,3,4,5])

In [148]:
to5[0]

1

In [149]:
to5[-1]

5

In [150]:
to5[:]

array([1, 2, 3, 4, 5])

In [151]:
to5[:2:]

array([1, 2])

In [152]:
to5[::-1]

array([5, 4, 3, 2, 1])

In [153]:
matriz3x3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [154]:
matriz3x3[:2,1:]

array([[2, 3],
       [5, 6]])

In [155]:
matriz3x3[2]

array([7, 8, 9])

In [156]:
matriz3x3[2,:]

array([7, 8, 9])

In [157]:
matriz3x3[2:,:]

array([[7, 8, 9]])

In [158]:
matriz3x3[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [159]:
matriz3x3[1,:2]

array([4, 5])

In [160]:
matriz3x3[0,0] = 10
matriz3x3

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

#### Slicing

In [161]:
to_slice = np.arange(50) *2

In [162]:
to_slice[5:10:2]

array([10, 14, 18])

In [163]:
to_slice[:4]

array([0, 2, 4, 6])

In [164]:
to_slice[4:]

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40,
       42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74,
       76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [165]:
to_slice[::3]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [166]:
to_slice[:3] = 1
to_slice

array([ 1,  1,  1,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#### copy

In [167]:
to_copy = to_slice.copy()
to_copy

array([ 1,  1,  1,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [168]:
to_slice == to_slice

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

#### Reshaping

In [169]:
to_reshape = np.array([
    [63,23,19],
    [41,87,10]
])
to_reshape

array([[63, 23, 19],
       [41, 87, 10]])

In [170]:
to_reshape.T

array([[63, 41],
       [23, 87],
       [19, 10]])

In [171]:
np.transpose(to_reshape)

array([[63, 41],
       [23, 87],
       [19, 10]])

#### Broadcasting

In [172]:
a = np.array([[33,34,35]])
a

array([[33, 34, 35]])

In [173]:
a.T

array([[33],
       [34],
       [35]])

In [174]:
a.T + a

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

#### Matriz para Vetores

In [175]:
matriz = np.array([np.arange(1,6), np.arange(10,15)])
matriz

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [176]:
matriz.ndim

2

In [177]:
matriz.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [178]:
matriz.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

#### Operadores Lógicos

In [179]:
mtrx_rnd = np.random.randint(1,10, size = (4,4))
mtrx_rnd

array([[8, 1, 6, 5],
       [4, 7, 5, 5],
       [1, 3, 8, 4],
       [6, 2, 2, 6]])

In [180]:
np.any(mtrx_rnd % 2==0)

True

In [181]:
np.all(mtrx_rnd < 10)

True

In [182]:
np.where(np.logical_and(mtrx_rnd[:,1]>2,mtrx_rnd[:,1]<9))

(array([1, 2]),)

In [183]:
np.intersect1d(np.where(mtrx_rnd[:,1]>2),np.where(mtrx_rnd[:,1]<9))

array([1, 2])

#### Reshaping

In [184]:
to_reshape = np.arange(1,16)
to_reshape

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [185]:
to_reshape.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### Sort

In [186]:
to_sort = np.array([
    [3,2],[10,-1]
])
to_sort

array([[ 3,  2],
       [10, -1]])

In [187]:
to_sort.sort(axis=1)
to_sort

array([[ 2,  3],
       [-1, 10]])

In [188]:
to_sort.sort(axis=0)
to_sort

array([[-1,  3],
       [ 2, 10]])